### ISSUE TITLE
`json_body` doesn't seem to be working for YAML mocks (standalone)

### ISSUE THREAD

**Issue by mdevino** [httpmock/httpmock#118]
Hi, I've just found the library and am trying to spin up a quick mock server.
I have the following YAML, but it doesn't seem to work as expected:

```yaml
when:
  method: GET
  path: /health
then:
  status: 200
  json_body: |-
    {
      "status": "healthy"
    }
```

When I invoke the endpoint, I do get a 200 back, but the response body is empty. Am I missing anything?

**Comment by mdevino** [comment]
I've installed version `0.7.0`, but `httpmock --version` outputs 0.6:

```sh
    Replaced package `httpmock v0.7.0` with `httpmock v0.7.0` (executable `httpmock`)
mdevino:mocks$ httpmock --version
httpmock 0.6
```

**Comment by mshytikov** [comment]
@mdevino Thank you for opening this issue. I encountered the same problem today while starting to use the library for the first time. Hope the new image will be available soon. 
As tmp workaround until the new docker image is available you can just replace ```json_body:``` with  just ```body:```

**Comment by mdevino** [comment]
Hi @alexliesenfeld. Thanks for the reply. Would `body` trim leading/trailing spaces (new lines, tabs, etc.)?

**Comment by alexliesenfeld** [comment]
No, it will respond with original content.

This definition:

```yaml
when:
  method: GET
then:
  status: 200
  body: '  hello  '
```

Will respond with:

```sh
curl localhost:5050
  hello  %                   
```
